services:
  - type: web
    name: data-analyst-agent-v2
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.13
